# Singular value decomposition

The SVD represents an expansion of the original data in the coord system where the covariance matrix is diagonal.

* $M$ be a $n \times p$
* $U$ be $n \times n$, the columns are left singular vectors (U is orthogonal)
* $S$ be $n \times p$ the diagonal contains the singular values
* $V$ be $p\times p$ the rows contain the right singular vectors (V is orthogonal)

$$
M = USV^T
$$

* $U^T = I_{n\times n}$
* $V^TV = I_{p\times p}$

## Steps

Find eigenvalues and eigenvectors of $AA^T$ and $A^TA$. The eigenvectors of $AA^T$ make up the columns of $U$, the eigenvectors of $A^TA$ make up the columns of $V$. The singular values are the diagonal entries of $S$ and are arranged in **descending** order.

In [42]:
import numpy as np

A = np.array([
        [3,2,2],
        [2,3,-2]
    ])

def svd(A):
    AAT = A @ np.transpose(A)
    U_v, U = np.linalg.eig(AAT)
    
    ATA = np.transpose(A) @ A
    _, V = np.linalg.eig(ATA)
    
    D = np.sqrt(U_v)
    return U, D, V
    
U, D, V = svd(A)



u, s, v = np.linalg.svd(A)

print(str(U) + " vs \n" + str(u))
print('---')
print(str(D) + " vs \n" + str(s))
print('---')
print(str(V) + " vs \n" + str(v))
print('---')

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] vs 
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
---
[ 5.  3.] vs 
[ 5.  3.]
---
[[ -7.07106781e-01  -6.66666667e-01   2.35702260e-01]
 [ -7.07106781e-01   6.66666667e-01  -2.35702260e-01]
 [ -1.16614446e-17   3.33333333e-01   9.42809042e-01]] vs 
[[ -7.07106781e-01  -7.07106781e-01   1.11022302e-16]
 [ -2.35702260e-01   2.35702260e-01  -9.42809042e-01]
 [ -6.66666667e-01   6.66666667e-01   3.33333333e-01]]
---
